### ISSUE TITLE
Downloading From Jellyfin Catalog or Manually Installing Gives Version 1.0

### ISSUE THREAD

**Issue by Computahwiz-Github** [Namo2/InPlayerEpisodePreview#12]
No matter how I download/install this plugin, it shows as version 1.0 in jellyfin. I disabled plugin updating as well and delete the plugin folder, and clear the cache, yet it still shows version 1.0.1 as 1.0.0. It showed the restart button once with the correct version after it recognized the web-client script. Then it reverted again to 1.0.0 after a restart. I have yet to see the settings panel work. Jellyfin version 10.8.13. Even the JMP shows the same behavior even though i manually installed JMP-Full in the extensions folder of the program. The one thing the JMP does is let me play an episode from the dropdown. however, it shows the titles and descriptions as undefined and won't let me click on anything except for the first episode. the season numbers show correctly. All directories were even given full permissions. Jellyfin is from LSIO in a docker container. Can provide logs if requested.

**Comment by Jermstain** [comment]
Tried to label it whoops lol.

UPDATE: JMP works with the web-client extension and without the plugin being present on the server. Still can't get the browser to work with it at all.

**Comment by Namo2** [comment]
Hey, sorry that you have issues with this plugin.

That the version in the plugin dashboard shows 1.0.0.0 is a known bug.
Also the JMP versions works without the server plugin by default.
That the description shows as undefined happens when there is no meta data for that episode, however that the title also shows this is unusual.

Does the preview button show at all in your browser? 
If not it would be nice if you could send the output of your browser console while starting an episode from the Jellyfin dashboard
or have a look for yourself, if you can see any lines starting with `[InPlayerEpisodePreview]`

I will have a look on this at thursday/friday

**Comment by Jermstain** [comment]
It's all good. Just wanted to reach out in case anyone else had issues or if I could help in some way.

Understood and yes it was a little odd because I do have nfo metadata for everything in my library. It only showed as undefined in on the website in a browser. JMP shows normally and works wonderfully (without the server plugin).

The preview button did indeed show in the browser, and I could get the first episode of the first season to show an image. Clicking any other season or episode made the dialog disappear.

I will look at my old logs to see what was going on or if I can send any part of it here.

Thanks for reaching back to me!
